### PR TITLE
Fix build issues causing SIGSEGV on first packet

### LINKED ISSUE #8: MySQL died after PHP send data to it.
Here is what I got in logs

```
2018-11-29  1:21:57 139656613899008 [Warning] IP address '172.18.0.1' could not be resolved: Name or service not known
181129  1:23:23 [ERROR] mysqld got signal 11 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
To report this bug, see https://mariadb.com/kb/en/reporting-bugs
We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.
Server version: 10.1.26-MariaDB
key_buffer_size=134217728
read_buffer_size=131072
max_used_connections=1
max_threads=153
thread_count=0
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 467133 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.
Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
```

After it, MySQL could not start and docker container goes in crush loop:

```
+ '[' mysqld = mysqld ']'
+ ln -snf /usr/libexec/mysqld /usr/local/bin
+ rm -rf /etc/my.cnf.d/auth_gssapi.cnf
+ mysql_install_db --rpm
my_print_defaults: [ERROR] unknown option '--mysqld'
2018-11-29  1:23:25 140014962817344 [Note] /usr/libexec/mysqld (mysqld 10.1.26-MariaDB) starting as process 18 ...
2018-11-29  1:23:29 140588855441728 [Note] /usr/libexec/mysqld (mysqld 10.1.26-MariaDB) starting as process 49 ...
2018-11-29  1:23:32 140083679729984 [Note] /usr/libexec/mysqld (mysqld 10.1.26-MariaDB) starting as process 79 ...
PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:
'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h b02202262875 password 'new-password'
Alternatively you can run:
'/usr/bin/mysql_secure_installation'
which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.
See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.
Please report any problems at http://mariadb.org/jira
The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/
+ chmod -R 777 /var/lib/mysql
+ pid=107
+ for i in '{10..0}'
+ mysqld --skip-networking -umysql
+ mysql
+ echo 'SELECT 1'
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
2018-11-29  1:23:35 139764970879296 [Note] mysqld (mysqld 10.1.26-MariaDB) starting as process 107 ...
2018-11-29 01:23:35 107 [Note] PINBA: engine initialized on 0.0.0.0:3002
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: The InnoDB memory heap is disabled
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Using Linux native AIO
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Using SSE crc32 instructions
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Completed initialization of buffer pool
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Highest supported file format is Barracuda.
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: 128 rollback segment(s) are active.
2018-11-29  1:23:35 139764970879296 [Note] InnoDB: Waiting for purge to start
2018-11-29  1:23:35 139764970879296 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.36-82.1 started; log sequence number 1616869
2018-11-29  1:23:35 139763868759808 [Note] InnoDB: Dumping buffer pool(s) not yet started
2018-11-29  1:23:35 139764970879296 [Note] Plugin 'FEEDBACK' is disabled.
2018-11-29  1:23:35 139764970879296 [Note] mysqld: ready for connections.
Version: '10.1.26-MariaDB'  socket: '/var/lib/mysql/mysql.sock'  port: 0  MariaDB Server
+ for i in '{10..0}'
+ mysql
+ echo 'SELECT 1'
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
+ for i in '{10..0}'
+ mysql
+ echo 'SELECT 1'
MySQL init process in progress...
+ echo 'MySQL init process in progress...'
+ sleep 1
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
MySQL init process in progress...
+ echo 'MySQL init process in progress...'
+ sleep 1
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
MySQL init process in progress...
+ echo 'MySQL init process in progress...'
+ sleep 1
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
+ echo 'MySQL init process in progress...'
+ sleep 1
MySQL init process in progress...
+ for i in '{10..0}'
+ echo 'SELECT 1'
+ mysql
+ echo 'MySQL init process in progress...'
MySQL init process in progress...
+ sleep 1
+ '[' 0 = 0 ']'
+ echo 'MySQL init process failed.'
MySQL init process failed.
+ exit 1
```

Following SQL was applied to MySQL. It was generated using https://github.com/badoo/pinba2/blob/master/scripts/convert_mysqldump.php

```
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' identified by '***';
update mysql.user set password=PASSWORD("***") where User='root';

CREATE USER IF NOT EXISTS 'manager'@'%' IDENTIFIED BY '***';
GRANT ALL PRIVILEGES ON * . * TO 'manager'@'%';

CREATE USER IF NOT EXISTS 'pinboard'@'%' IDENTIFIED BY '***';
GRANT ALL PRIVILEGES ON * . * TO 'pinboard'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS pinba DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;

use pinba;

DROP TABLE IF EXISTS report_by_script_name;

CREATE TABLE `report_by_script_name` (
  `script_name` varchar(128) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~script/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_server_name;

CREATE TABLE `report_by_server_name` (
  `server_name` varchar(64) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~server/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname;

CREATE TABLE `report_by_hostname` (
  `hostname` varchar(32) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_server_and_script;

CREATE TABLE `report_by_server_and_script` (
  `server_name` varchar(64) NOT NULL,
  `script_name` varchar(128) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~server,~script/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_and_script;

CREATE TABLE `report_by_hostname_and_script` (
  `hostname` varchar(32) NOT NULL,
  `script_name` varchar(128) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~script/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_and_server;

CREATE TABLE `report_by_hostname_and_server` (
  `hostname` varchar(32) NOT NULL,
  `server_name` varchar(64) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~server/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_server_and_script;

CREATE TABLE `report_by_hostname_server_and_script` (
  `hostname` varchar(32) NOT NULL,
  `server_name` varchar(64) NOT NULL,
  `script_name` varchar(128) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~server,~script/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_status;

CREATE TABLE `report_by_status` (
  `status` int(11) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~status/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_script_and_status;

CREATE TABLE `report_by_script_and_status` (
  `script_name` varchar(128) NOT NULL,
  `status` int(11) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~script,~status/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_server_and_status;

CREATE TABLE `report_by_server_and_status` (
  `server_name` varchar(64) NOT NULL,
  `status` int(11) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~server,~status/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_and_status;

CREATE TABLE `report_by_hostname_and_status` (
  `hostname` varchar(32) NOT NULL,
  `status` int(11) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~status/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_script_and_status;

CREATE TABLE `report_by_hostname_script_and_status` (
  `hostname` varchar(32) NOT NULL,
  `script_name` varchar(128) NOT NULL,
  `status` int(11) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~script,~status/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_schema;

CREATE TABLE `report_by_schema` (
  `schema` varchar(16) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~schema/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_script_and_schema;

CREATE TABLE `report_by_script_and_schema` (
  `script_name` varchar(128) NOT NULL,
  `schema` varchar(16) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~script,~schema/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_server_and_schema;

CREATE TABLE `report_by_server_and_schema` (
  `server_name` varchar(64) NOT NULL,
  `schema` varchar(16) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~server,~schema/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_and_schema;

CREATE TABLE `report_by_hostname_and_schema` (
  `hostname` varchar(32) NOT NULL,
  `schema` varchar(16) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~schema/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_script_and_schema;

CREATE TABLE `report_by_hostname_script_and_schema` (
  `hostname` varchar(32) NOT NULL,
  `script_name` varchar(128) NOT NULL,
  `schema` varchar(16) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~script,~schema/hv=0:60000:32768,p50/no_filters';

DROP TABLE IF EXISTS report_by_hostname_status_and_schema;

CREATE TABLE `report_by_hostname_status_and_schema` (
  `hostname` varchar(32) NOT NULL,
  `status` int(11) NOT NULL,
  `schema` varchar(16) NOT NULL,
  `req_count` int(10) unsigned NOT NULL,
  `req_per_sec` float NOT NULL,
  `req_time_total` float NOT NULL,
  `req_time_per_sec` float NOT NULL,
  `ru_utime_total` float NOT NULL,
  `ru_utime_per_sec` float NOT NULL,
  `ru_stime_total` float NOT NULL,
  `ru_stime_per_sec` float NOT NULL,
  `traffic_total` bigint(20) unsigned NOT NULL,
  `traffic_per_sec` float NOT NULL,
  `memory_footprint` bigint(20) NOT NULL,
  `p50` float NOT NULL
) ENGINE=PINBA DEFAULT CHARSET=latin1 COMMENT='v2/request/default_history_time/~host,~status,~schema/hv=0:60000:32768,p50/no_filters';
```

Tables like `request`, `tag`, `timer`,  `timertag`, `info` and `status` were not converted by script and were not created in new MySQL.

Here are details about used PHP version

```
PHP 7.2.11 (cli) (built: Oct 15 2018 18:55:39) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11, Copyright (c) 1999-2018, by Zend Technologies
```

and `pinba` extention:

```
Extension [ <persistent> extension #49 pinba version 1.1.2-dev ] {

  - INI {
    Entry [ pinba.server <ALL> ]
      Current = '127.0.0.1:3002'
    }
    Entry [ pinba.enabled <ALL> ]
      Current = '1'
    }
    Entry [ pinba.auto_flush <ALL> ]
      Current = '1'
    }
  }

  - Constants [5] {
    Constant [ integer PINBA_FLUSH_ONLY_STOPPED_TIMERS ] { 1 }
    Constant [ integer PINBA_FLUSH_RESET_DATA ] { 2 }
    Constant [ integer PINBA_ONLY_STOPPED_TIMERS ] { 1 }
    Constant [ integer PINBA_ONLY_RUNNING_TIMERS ] { 4 }
    Constant [ integer PINBA_AUTO_FLUSH ] { 8 }
  }

  - Functions {
    Function [ <internal:pinba> function pinba_timer_start ] {

      - Parameters [3] {
        Parameter #0 [ <required> $tags ]
        Parameter #1 [ <optional> $data ]
        Parameter #2 [ <optional> $hit_count ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_add ] {

      - Parameters [3] {
        Parameter #0 [ <required> $tags ]
        Parameter #1 [ <required> $value ]
        Parameter #2 [ <optional> $data ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_stop ] {

      - Parameters [1] {
        Parameter #0 [ <required> $timer ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_delete ] {

      - Parameters [1] {
        Parameter #0 [ <required> $timer ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_data_merge ] {

      - Parameters [2] {
        Parameter #0 [ <required> $timer ]
        Parameter #1 [ <required> $data ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_data_replace ] {

      - Parameters [2] {
        Parameter #0 [ <required> $timer ]
        Parameter #1 [ <required> $data ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_tags_merge ] {

      - Parameters [2] {
        Parameter #0 [ <required> $timer ]
        Parameter #1 [ <required> $tags ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_tags_replace ] {

      - Parameters [2] {
        Parameter #0 [ <required> $timer ]
        Parameter #1 [ <required> $tags ]
      }
    }
    Function [ <internal:pinba> function pinba_flush ] {

      - Parameters [2] {
        Parameter #0 [ <optional> $custom_script_name ]
        Parameter #1 [ <optional> $flags ]
      }
    }
    Function [ <internal:pinba> function pinba_reset ] {

      - Parameters [0] {
      }
    }
    Function [ <internal:pinba> function pinba_get_info ] {

      - Parameters [0] {
      }
    }
    Function [ <internal:pinba> function pinba_get_data ] {

      - Parameters [1] {
        Parameter #0 [ <optional> $flags ]
      }
    }
    Function [ <internal:pinba> function pinba_timer_get_info ] {

      - Parameters [1] {
        Parameter #0 [ <required> $timer ]
      }
    }
    Function [ <internal:pinba> function pinba_timers_stop ] {

      - Parameters [0] {
      }
    }
    Function [ <internal:pinba> function pinba_timers_get ] {

      - Parameters [0] {
      }
    }
    Function [ <internal:pinba> function pinba_script_name_set ] {

      - Parameters [1] {
        Parameter #0 [ <required> $custom_script_name ]
      }
    }
    Function [ <internal:pinba> function pinba_hostname_set ] {

      - Parameters [1] {
        Parameter #0 [ <required> $custom_hostname ]
      }
    }
    Function [ <internal:pinba> function pinba_server_name_set ] {

      - Parameters [1] {
        Parameter #0 [ <required> $custom_server_name ]
      }
    }
    Function [ <internal:pinba> function pinba_schema_set ] {

      - Parameters [1] {
        Parameter #0 [ <required> $custom_schema ]
      }
    }
    Function [ <internal:pinba> function pinba_request_time_set ] {

      - Parameters [1] {
        Parameter #0 [ <required> $request_time ]
      }
    }
    Function [ <internal:pinba> function pinba_tag_set ] {

      - Parameters [2] {
        Parameter #0 [ <required> $tag ]
        Parameter #1 [ <required> $value ]
      }
    }
    Function [ <internal:pinba> function pinba_tag_get ] {

      - Parameters [1] {
        Parameter #0 [ <required> $tag ]
      }
    }
    Function [ <internal:pinba> function pinba_tag_delete ] {

      - Parameters [1] {
        Parameter #0 [ <required> $tag ]
      }
    }
    Function [ <internal:pinba> function pinba_tags_get ] {

      - Parameters [0] {
      }
    }
  }

  - Classes [1] {
    Class [ <internal:pinba> class PinbaClient ] {

      - Constants [0] {
      }

      - Static properties [0] {
      }

      - Static methods [0] {
      }

      - Properties [0] {
      }

      - Methods [17] {
        Method [ <internal:pinba, ctor> public method __construct ] {

          - Parameters [1] {
            Parameter #0 [ <required> $servers ]
          }
        }

        Method [ <internal:pinba> public method setHostname ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setScriptname ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setServername ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setRequestCount ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setDocumentSize ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setMemoryPeak ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setMemoryFootprint ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setRusage ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setRequestTime ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setStatus ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setSchema ] {

          - Parameters [1] {
            Parameter #0 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setTag ] {

          - Parameters [2] {
            Parameter #0 [ <required> $tag ]
            Parameter #1 [ <required> $value ]
          }
        }

        Method [ <internal:pinba> public method setTimer ] {

          - Parameters [4] {
            Parameter #0 [ <required> $tags ]
            Parameter #1 [ <required> $value ]
            Parameter #2 [ <optional> $rusage ]
            Parameter #3 [ <optional> $hit_count ]
          }
        }

        Method [ <internal:pinba> public method addTimer ] {

          - Parameters [4] {
            Parameter #0 [ <required> $tags ]
            Parameter #1 [ <required> $value ]
            Parameter #2 [ <optional> $rusage ]
            Parameter #3 [ <optional> $hit_count ]
          }
        }

        Method [ <internal:pinba> public method send ] {

          - Parameters [1] {
            Parameter #0 [ <optional> $flags ]
          }
        }

        Method [ <internal:pinba> public method getData ] {

          - Parameters [1] {
            Parameter #0 [ <optional> $flags ]
          }
        }
      }
    }
  }
}
```

MySQL crushed after first fpm request was processed. Please send help.

### PR DESCRIPTION
**Pull request by anton-povarov**
This one should fix #8 'short term'.

There is an issue with build + t1ha, my kung fu is not strong enough to address it directly, but was able to sidestep it by updating t1ha and linking the final shared library directly with it (instead of just compiling source files into libpinba.a).

### CODE REVIEW

**Comment by anton-povarov** [comment]
@mkevac please review whenever convenient.

can test like this

1. `docker build -t pinba2-dev:latest .`
2. `docker run --rm --net=host --privileged pinba2-dev` // privileged not required here i think
3. `mysql -h127.0.0.1 -uroot` and create a table (described in linked issue 1st comment for example)
4. then i just run a simple go program sending pinba packets :) will post if needed
5. select from table should show some data you sent

**Comment by anton-povarov** [comment]
Also got this on container shutdown via ```kill -TERM `pidof mysqld` ```

```
2018-12-12 13:23:22 1 [Note] PINBA: udp_reader/1; received shutdown request
2018-12-12 13:23:22 1 [Note] PINBA: udp_reader/0; received shutdown request
terminate called without an active exception
181212 13:23:22 [ERROR] mysqld got signal 6 ;
```

it's probably unrelated to this issue, but to the improper init failure handling i've been fixing on master.

**Comment by mkevac** [comment]
@anton-povarov I could not build pinba after the fix.
```

**Comment by anton-povarov** [comment]
Marko said - it builds fine.

**Pull request merged**
